"""initial events tables

Revision ID: d75ca2f07cb4
Revises:
Create Date: 2026-09-30 18:06:18.439166
"""

import sqlalchemy as sa
from alembic import op

revision = "d75ca2f07cb4"
down_revision = None
branch_labels = ("events",)
depends_on = ("694091f4034e", "ba3688dc8663")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events_calendar_tokens",
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_events_calendar_tokens_member_id_core_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("member_id", name=op.f("pk_events_calendar_tokens")),
        info={"module": "events"},
    )
    with op.batch_alter_table("events_calendar_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_calendar_tokens_token"), ["token"], unique=True)

    op.create_table(
        "events_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("zone", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("leader_id", sa.Integer(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("min_level", sa.Integer(), nullable=True),
        sa.Column("max_level", sa.Integer(), nullable=True),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("series_id", sa.String(length=40), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("discord_channel_id", sa.String(length=30), nullable=True),
        sa.Column("discord_message_id", sa.String(length=30), nullable=True),
        sa.Column("reminded", sa.Boolean(), nullable=False),
        sa.Column("start_announced", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["core_members.id"], name=op.f("fk_events_events_created_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["leader_id"],
            ["core_members.id"],
            name=op.f("fk_events_events_leader_id_core_members"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events_events")),
        info={"module": "events"},
    )
    with op.batch_alter_table("events_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_events_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_events_series_id"), ["series_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_events_starts_at"), ["starts_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_events_status"), ["status"], unique=False)

    op.create_table(
        "events_attendance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("recorded_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core_characters.id"],
            name=op.f("fk_events_attendance_character_id_core_characters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events_events.id"],
            name=op.f("fk_events_attendance_event_id_events_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_events_attendance_member_id_core_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"], ["core_members.id"], name=op.f("fk_events_attendance_recorded_by_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events_attendance")),
        sa.UniqueConstraint("event_id", "member_id", name=op.f("uq_events_attendance_event_id")),
        info={"module": "events"},
    )
    with op.batch_alter_table("events_attendance", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_attendance_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_attendance_member_id"), ["member_id"], unique=False)

    op.create_table(
        "events_loot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.String(length=120), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("character_name", sa.String(length=64), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("points", sa.Float(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("awarded_by", sa.Integer(), nullable=True),
        sa.Column("awarded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["awarded_by"], ["core_members.id"], name=op.f("fk_events_loot_awarded_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core_characters.id"],
            name=op.f("fk_events_loot_character_id_core_characters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events_events.id"], name=op.f("fk_events_loot_event_id_events_events"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["archive_items.id"], name=op.f("fk_events_loot_item_id_archive_items"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["core_members.id"], name=op.f("fk_events_loot_member_id_core_members"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events_loot")),
        info={"module": "events"},
    )
    with op.batch_alter_table("events_loot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_loot_awarded_at"), ["awarded_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_loot_character_id"), ["character_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_loot_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_loot_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_loot_member_id"), ["member_id"], unique=False)

    op.create_table(
        "events_signups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core_characters.id"],
            name=op.f("fk_events_signups_character_id_core_characters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events_events.id"],
            name=op.f("fk_events_signups_event_id_events_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_events_signups_member_id_core_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events_signups")),
        sa.UniqueConstraint("event_id", "member_id", name=op.f("uq_events_signups_event_id")),
        info={"module": "events"},
    )
    with op.batch_alter_table("events_signups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_signups_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_signups_member_id"), ["member_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events_signups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_signups_member_id"))
        batch_op.drop_index(batch_op.f("ix_events_signups_event_id"))

    op.drop_table("events_signups")
    with op.batch_alter_table("events_loot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_loot_member_id"))
        batch_op.drop_index(batch_op.f("ix_events_loot_item_id"))
        batch_op.drop_index(batch_op.f("ix_events_loot_event_id"))
        batch_op.drop_index(batch_op.f("ix_events_loot_character_id"))
        batch_op.drop_index(batch_op.f("ix_events_loot_awarded_at"))

    op.drop_table("events_loot")
    with op.batch_alter_table("events_attendance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_attendance_member_id"))
        batch_op.drop_index(batch_op.f("ix_events_attendance_event_id"))

    op.drop_table("events_attendance")
    with op.batch_alter_table("events_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_events_status"))
        batch_op.drop_index(batch_op.f("ix_events_events_starts_at"))
        batch_op.drop_index(batch_op.f("ix_events_events_series_id"))
        batch_op.drop_index(batch_op.f("ix_events_events_kind"))

    op.drop_table("events_events")
    with op.batch_alter_table("events_calendar_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_calendar_tokens_token"))

    op.drop_table("events_calendar_tokens")
    # ### end Alembic commands ###
