"""initial watch tables

Revision ID: d9a36ea23a2f
Revises:
Create Date: 2026-09-30 18:06:22.421265
"""

import sqlalchemy as sa
from alembic import op

revision = "d9a36ea23a2f"
down_revision = None
branch_labels = ("watch",)
depends_on = "694091f4034e"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watch_timers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creature", sa.String(length=120), nullable=False),
        sa.Column("creature_key", sa.String(length=120), nullable=False),
        sa.Column("zone", sa.String(length=120), nullable=True),
        sa.Column("respawn_minutes", sa.Integer(), nullable=False),
        sa.Column("variance_minutes", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["core_members.id"], name=op.f("fk_watch_timers_created_by_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_timers")),
        info={"module": "watch"},
    )
    with op.batch_alter_table("watch_timers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watch_timers_creature_key"), ["creature_key"], unique=True)

    op.create_table(
        "watch_camps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zone", sa.String(length=120), nullable=False),
        sa.Column("camp", sa.String(length=120), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column("character_name", sa.String(length=64), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("end_reason", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core_characters.id"],
            name=op.f("fk_watch_camps_character_id_core_characters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["core_members.id"], name=op.f("fk_watch_camps_member_id_core_members"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_camps")),
        info={"module": "watch"},
    )
    with op.batch_alter_table("watch_camps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watch_camps_ended_at"), ["ended_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_watch_camps_started_at"), ["started_at"], unique=False)

    op.create_table(
        "watch_deaths",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timer_id", sa.Integer(), nullable=False),
        sa.Column("died_at", sa.DateTime(), nullable=False),
        sa.Column("reported_by", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("soon_sent", sa.Boolean(), nullable=False),
        sa.Column("open_sent", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reported_by"], ["core_members.id"], name=op.f("fk_watch_deaths_reported_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["timer_id"], ["watch_timers.id"], name=op.f("fk_watch_deaths_timer_id_watch_timers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_deaths")),
        info={"module": "watch"},
    )
    with op.batch_alter_table("watch_deaths", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watch_deaths_died_at"), ["died_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_watch_deaths_timer_id"), ["timer_id"], unique=False)

    op.create_table(
        "watch_watchers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timer_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_watch_watchers_member_id_core_members"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["timer_id"], ["watch_timers.id"], name=op.f("fk_watch_watchers_timer_id_watch_timers"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_watchers")),
        sa.UniqueConstraint("timer_id", "member_id", name=op.f("uq_watch_watchers_timer_id")),
        info={"module": "watch"},
    )
    with op.batch_alter_table("watch_watchers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watch_watchers_member_id"), ["member_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_watch_watchers_timer_id"), ["timer_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watch_watchers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watch_watchers_timer_id"))
        batch_op.drop_index(batch_op.f("ix_watch_watchers_member_id"))

    op.drop_table("watch_watchers")
    with op.batch_alter_table("watch_deaths", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watch_deaths_timer_id"))
        batch_op.drop_index(batch_op.f("ix_watch_deaths_died_at"))

    op.drop_table("watch_deaths")
    with op.batch_alter_table("watch_camps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watch_camps_started_at"))
        batch_op.drop_index(batch_op.f("ix_watch_camps_ended_at"))

    op.drop_table("watch_camps")
    with op.batch_alter_table("watch_timers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watch_timers_creature_key"))

    op.drop_table("watch_timers")
    # ### end Alembic commands ###
