"""initial core tables

Revision ID: 694091f4034e
Revises:
Create Date: 2026-09-30 18:05:57.510871
"""

import sqlalchemy as sa
from alembic import op

revision = "694091f4034e"
down_revision = None
branch_labels = ("core",)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("onboarded", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_members")),
        info={"module": "core"},
    )
    op.create_table(
        "core_api_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("prefix", sa.String(length=12), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_core_api_tokens_member_id_core_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_core_api_tokens_token_hash")),
        info={"module": "core"},
    )
    with op.batch_alter_table("core_api_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_api_tokens_member_id"), ["member_id"], unique=False)

    op.create_table(
        "core_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("via", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=True),
        sa.Column("entity_id", sa.String(length=60), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["core_members.id"], name=op.f("fk_core_audit_log_actor_id_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_audit_log")),
        info={"module": "core"},
    )
    with op.batch_alter_table("core_audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_core_audit_log_at"), ["at"], unique=False)

    op.create_table(
        "core_characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("class_name", sa.String(length=40), nullable=True),
        sa.Column("race", sa.String(length=40), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("server", sa.String(length=40), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("is_bank_mule", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_core_characters_member_id_core_members"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_characters")),
        sa.UniqueConstraint("name", "server", name=op.f("uq_core_characters_name")),
        info={"module": "core"},
    )
    with op.batch_alter_table("core_characters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_characters_member_id"), ["member_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_core_characters_name"), ["name"], unique=False)

    op.create_table(
        "core_identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_core_identities_member_id_core_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_identities")),
        sa.UniqueConstraint("provider", "subject", name=op.f("uq_core_identities_provider")),
        info={"module": "core"},
    )
    with op.batch_alter_table("core_identities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_identities_member_id"), ["member_id"], unique=False)

    op.create_table(
        "core_link_codes",
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_core_link_codes_member_id_core_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_core_link_codes")),
        info={"module": "core"},
    )
    op.create_table(
        "core_notices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=400), nullable=False),
        sa.Column("url", sa.String(length=300), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"], ["core_members.id"], name=op.f("fk_core_notices_member_id_core_members"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_notices")),
        info={"module": "core"},
    )
    with op.batch_alter_table("core_notices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_notices_member_id"), ["member_id"], unique=False)

    op.create_table(
        "core_role_grants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_core_role_grants_member_id_core_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_role_grants")),
        sa.UniqueConstraint("member_id", "role", name=op.f("uq_core_role_grants_member_id")),
        info={"module": "core"},
    )
    with op.batch_alter_table("core_role_grants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_role_grants_member_id"), ["member_id"], unique=False)

    op.create_table(
        "core_settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["core_members.id"], name=op.f("fk_core_settings_updated_by_core_members")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_core_settings")),
        info={"module": "core"},
    )
    op.create_table(
        "core_uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("path", sa.String(length=300), nullable=False),
        sa.Column("mime", sa.String(length=60), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["core_members.id"], name=op.f("fk_core_uploads_uploaded_by_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_uploads")),
        info={"module": "core"},
    )
    with op.batch_alter_table("core_uploads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_uploads_sha256"), ["sha256"], unique=False)

    op.create_table(
        "core_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.String(length=300), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("decided_by", sa.Integer(), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("result_ref", sa.String(length=120), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["core_members.id"], name=op.f("fk_core_proposals_created_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["core_members.id"], name=op.f("fk_core_proposals_decided_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"], ["core_uploads.id"], name=op.f("fk_core_proposals_upload_id_core_uploads")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_proposals")),
        info={"module": "core"},
    )
    with op.batch_alter_table("core_proposals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_proposals_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_core_proposals_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("core_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_proposals_status"))
        batch_op.drop_index(batch_op.f("ix_core_proposals_kind"))

    op.drop_table("core_proposals")
    with op.batch_alter_table("core_uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_uploads_sha256"))

    op.drop_table("core_uploads")
    op.drop_table("core_settings")
    with op.batch_alter_table("core_role_grants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_role_grants_member_id"))

    op.drop_table("core_role_grants")
    with op.batch_alter_table("core_notices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_notices_member_id"))

    op.drop_table("core_notices")
    op.drop_table("core_link_codes")
    with op.batch_alter_table("core_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_identities_member_id"))

    op.drop_table("core_identities")
    with op.batch_alter_table("core_characters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_characters_name"))
        batch_op.drop_index(batch_op.f("ix_core_characters_member_id"))

    op.drop_table("core_characters")
    with op.batch_alter_table("core_audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_audit_log_at"))
        batch_op.drop_index(batch_op.f("ix_core_audit_log_action"))

    op.drop_table("core_audit_log")
    with op.batch_alter_table("core_api_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_api_tokens_member_id"))

    op.drop_table("core_api_tokens")
    op.drop_table("core_members")
    # ### end Alembic commands ###
