"""initial archive tables

Revision ID: ba3688dc8663
Revises:
Create Date: 2026-09-30 18:06:05.039663
"""

import sqlalchemy as sa
from alembic import op

revision = "ba3688dc8663"
down_revision = None
branch_labels = ("archive",)
depends_on = "694091f4034e"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_key", sa.String(length=120), nullable=False),
        sa.Column("item_type", sa.String(length=40), nullable=True),
        sa.Column("slots", sa.JSON(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("classes", sa.JSON(), nullable=False),
        sa.Column("races", sa.JSON(), nullable=False),
        sa.Column("skill", sa.String(length=20), nullable=True),
        sa.Column("damage", sa.Integer(), nullable=True),
        sa.Column("delay", sa.Integer(), nullable=True),
        sa.Column("ac", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("size", sa.String(length=20), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.Column("resists", sa.JSON(), nullable=False),
        sa.Column("effects", sa.JSON(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("patch_seen", sa.String(length=40), nullable=True),
        sa.Column("first_cataloged_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["first_cataloged_by"], ["core_members.id"], name=op.f("fk_archive_items_first_cataloged_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["core_members.id"], name=op.f("fk_archive_items_updated_by_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_archive_items")),
        info={"module": "archive"},
    )
    with op.batch_alter_table("archive_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_archive_items_name_key"), ["name_key"], unique=True)

    op.create_table(
        "archive_drop_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("creature", sa.String(length=120), nullable=True),
        sa.Column("zone", sa.String(length=120), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("reported_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["archive_items.id"],
            name=op.f("fk_archive_drop_reports_item_id_archive_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reported_by"], ["core_members.id"], name=op.f("fk_archive_drop_reports_reported_by_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_archive_drop_reports")),
        info={"module": "archive"},
    )
    with op.batch_alter_table("archive_drop_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_archive_drop_reports_creature"), ["creature"], unique=False)
        batch_op.create_index(batch_op.f("ix_archive_drop_reports_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_archive_drop_reports_zone"), ["zone"], unique=False)

    op.create_table(
        "archive_item_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("added_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by"], ["core_members.id"], name=op.f("fk_archive_item_images_added_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["archive_items.id"],
            name=op.f("fk_archive_item_images_item_id_archive_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"], ["core_uploads.id"], name=op.f("fk_archive_item_images_upload_id_core_uploads")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_archive_item_images")),
        info={"module": "archive"},
    )
    with op.batch_alter_table("archive_item_images", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_archive_item_images_item_id"), ["item_id"], unique=False)

    op.create_table(
        "archive_item_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("editor_id", sa.Integer(), nullable=True),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editor_id"], ["core_members.id"], name=op.f("fk_archive_item_revisions_editor_id_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["archive_items.id"],
            name=op.f("fk_archive_item_revisions_item_id_archive_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_archive_item_revisions")),
        info={"module": "archive"},
    )
    with op.batch_alter_table("archive_item_revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_archive_item_revisions_item_id"), ["item_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("archive_item_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_archive_item_revisions_item_id"))

    op.drop_table("archive_item_revisions")
    with op.batch_alter_table("archive_item_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_archive_item_images_item_id"))

    op.drop_table("archive_item_images")
    with op.batch_alter_table("archive_drop_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_archive_drop_reports_zone"))
        batch_op.drop_index(batch_op.f("ix_archive_drop_reports_item_id"))
        batch_op.drop_index(batch_op.f("ix_archive_drop_reports_creature"))

    op.drop_table("archive_drop_reports")
    with op.batch_alter_table("archive_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_archive_items_name_key"))

    op.drop_table("archive_items")
    # ### end Alembic commands ###
