"""initial board tables

Revision ID: 4eacf4afd871
Revises:
Create Date: 2026-09-30 18:06:11.519620
"""

import sqlalchemy as sa
from alembic import op

revision = "4eacf4afd871"
down_revision = None
branch_labels = ("board",)
depends_on = ("694091f4034e", "ba3688dc8663")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board_listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=3), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("name_key", sa.String(length=120), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("price", sa.String(length=60), nullable=True),
        sa.Column("server", sa.String(length=40), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("discord_channel_id", sa.String(length=30), nullable=True),
        sa.Column("discord_message_id", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["core_members.id"], name=op.f("fk_board_listings_author_id_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["archive_items.id"], name=op.f("fk_board_listings_item_id_archive_items"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_board_listings")),
        info={"module": "board"},
    )
    with op.batch_alter_table("board_listings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_board_listings_author_id"), ["author_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_board_listings_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_board_listings_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_board_listings_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_board_listings_name_key"), ["name_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_board_listings_status"), ["status"], unique=False)

    op.create_table(
        "board_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("item_name", sa.String(length=120), nullable=True),
        sa.Column("tradeskill", sa.String(length=60), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("claimed_by", sa.Integer(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("done_at", sa.DateTime(), nullable=True),
        sa.Column("thanked_at", sa.DateTime(), nullable=True),
        sa.Column("discord_channel_id", sa.String(length=30), nullable=True),
        sa.Column("discord_message_id", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["core_members.id"], name=op.f("fk_board_requests_author_id_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["claimed_by"], ["core_members.id"], name=op.f("fk_board_requests_claimed_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["archive_items.id"], name=op.f("fk_board_requests_item_id_archive_items"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_board_requests")),
        info={"module": "board"},
    )
    with op.batch_alter_table("board_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_board_requests_author_id"), ["author_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_board_requests_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_board_requests_claimed_by"), ["claimed_by"], unique=False)
        batch_op.create_index(batch_op.f("ix_board_requests_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("board_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_board_requests_status"))
        batch_op.drop_index(batch_op.f("ix_board_requests_claimed_by"))
        batch_op.drop_index(batch_op.f("ix_board_requests_category"))
        batch_op.drop_index(batch_op.f("ix_board_requests_author_id"))

    op.drop_table("board_requests")
    with op.batch_alter_table("board_listings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_board_listings_status"))
        batch_op.drop_index(batch_op.f("ix_board_listings_name_key"))
        batch_op.drop_index(batch_op.f("ix_board_listings_kind"))
        batch_op.drop_index(batch_op.f("ix_board_listings_item_id"))
        batch_op.drop_index(batch_op.f("ix_board_listings_expires_at"))
        batch_op.drop_index(batch_op.f("ix_board_listings_author_id"))

    op.drop_table("board_listings")
    # ### end Alembic commands ###
