"""initial ledger_sync tables

Revision ID: 9b2f1268e619
Revises:
Create Date: 2026-09-30 18:06:29.565035
"""

import sqlalchemy as sa
from alembic import op

revision = "9b2f1268e619"
down_revision = None
branch_labels = ("ledger_sync",)
depends_on = "694091f4034e"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_sync_imports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("character", sa.String(length=80), nullable=False),
        sa.Column("server", sa.String(length=80), nullable=False),
        sa.Column("received", sa.Integer(), nullable=False),
        sa.Column("duplicates", sa.Integer(), nullable=False),
        sa.Column("counts", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"], ["core_members.id"], name=op.f("fk_ledger_sync_imports_member_id_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_sync_imports")),
        info={"module": "ledger_sync"},
    )
    with op.batch_alter_table("ledger_sync_imports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ledger_sync_imports_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_ledger_sync_imports_member_id"), ["member_id"], unique=False)

    op.create_table(
        "ledger_sync_seen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"], ["core_members.id"], name=op.f("fk_ledger_sync_seen_member_id_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_sync_seen")),
        info={"module": "ledger_sync"},
    )
    with op.batch_alter_table("ledger_sync_seen", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ledger_sync_seen_event_hash"), ["event_hash"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_sync_seen", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ledger_sync_seen_event_hash"))

    op.drop_table("ledger_sync_seen")
    with op.batch_alter_table("ledger_sync_imports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ledger_sync_imports_member_id"))
        batch_op.drop_index(batch_op.f("ix_ledger_sync_imports_created_at"))

    op.drop_table("ledger_sync_imports")
    # ### end Alembic commands ###
