"""initial overlay tables

Revision ID: a0d1aa256c55
Revises:
Create Date: 2026-09-30 18:06:26.024845
"""

import sqlalchemy as sa
from alembic import op

revision = "a0d1aa256c55"
down_revision = None
branch_labels = ("overlay",)
depends_on = "694091f4034e"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "overlay_scenes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("position", sa.String(length=20), nullable=False),
        sa.Column("theme", sa.String(length=20), nullable=False),
        sa.Column("scale", sa.Integer(), nullable=False),
        sa.Column("card_seconds", sa.Integer(), nullable=False),
        sa.Column("timers_count", sa.Integer(), nullable=False),
        sa.Column("feeds", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["core_members.id"], name=op.f("fk_overlay_scenes_created_by_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_overlay_scenes")),
        info={"module": "overlay"},
    )
    with op.batch_alter_table("overlay_scenes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_overlay_scenes_token"), ["token"], unique=True)

    op.create_table(
        "overlay_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("scene_id", sa.Integer(), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["core_members.id"], name=op.f("fk_overlay_messages_actor_id_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["overlay_scenes.id"],
            name=op.f("fk_overlay_messages_scene_id_overlay_scenes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_overlay_messages")),
        info={"module": "overlay"},
    )
    with op.batch_alter_table("overlay_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_overlay_messages_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_overlay_messages_feed"), ["feed"], unique=False)
        batch_op.create_index(batch_op.f("ix_overlay_messages_scene_id"), ["scene_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("overlay_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_overlay_messages_scene_id"))
        batch_op.drop_index(batch_op.f("ix_overlay_messages_feed"))
        batch_op.drop_index(batch_op.f("ix_overlay_messages_created_at"))

    op.drop_table("overlay_messages")
    with op.batch_alter_table("overlay_scenes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_overlay_scenes_token"))

    op.drop_table("overlay_scenes")
    # ### end Alembic commands ###
