"""initial crafters tables

Revision ID: 006721c4cc3c
Revises:
Create Date: 2026-09-30 18:06:15.009523
"""

import sqlalchemy as sa
from alembic import op

revision = "006721c4cc3c"
down_revision = None
branch_labels = ("crafters",)
depends_on = ("694091f4034e", "ba3688dc8663")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crafters_recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill", sa.String(length=60), nullable=False),
        sa.Column("result_item_id", sa.Integer(), nullable=True),
        sa.Column("result_name", sa.String(length=120), nullable=False),
        sa.Column("yield_qty", sa.Integer(), nullable=False),
        sa.Column("trivial", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["core_members.id"], name=op.f("fk_crafters_recipes_created_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["result_item_id"],
            ["archive_items.id"],
            name=op.f("fk_crafters_recipes_result_item_id_archive_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crafters_recipes")),
        info={"module": "crafters"},
    )
    with op.batch_alter_table("crafters_recipes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crafters_recipes_result_item_id"), ["result_item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_crafters_recipes_result_name"), ["result_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_crafters_recipes_skill"), ["skill"], unique=False)

    op.create_table(
        "crafters_skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("skill", sa.String(length=60), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("specialty", sa.String(length=300), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core_characters.id"],
            name=op.f("fk_crafters_skills_character_id_core_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["core_members.id"], name=op.f("fk_crafters_skills_updated_by_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crafters_skills")),
        sa.UniqueConstraint("character_id", "skill", name=op.f("uq_crafters_skills_character_id")),
        info={"module": "crafters"},
    )
    with op.batch_alter_table("crafters_skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crafters_skills_character_id"), ["character_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_crafters_skills_skill"), ["skill"], unique=False)

    op.create_table(
        "crafters_recipe_components",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["archive_items.id"],
            name=op.f("fk_crafters_recipe_components_item_id_archive_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["crafters_recipes.id"],
            name=op.f("fk_crafters_recipe_components_recipe_id_crafters_recipes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crafters_recipe_components")),
        info={"module": "crafters"},
    )
    with op.batch_alter_table("crafters_recipe_components", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crafters_recipe_components_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_crafters_recipe_components_recipe_id"), ["recipe_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crafters_recipe_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crafters_recipe_components_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_crafters_recipe_components_item_id"))

    op.drop_table("crafters_recipe_components")
    with op.batch_alter_table("crafters_skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crafters_skills_skill"))
        batch_op.drop_index(batch_op.f("ix_crafters_skills_character_id"))

    op.drop_table("crafters_skills")
    with op.batch_alter_table("crafters_recipes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crafters_recipes_skill"))
        batch_op.drop_index(batch_op.f("ix_crafters_recipes_result_name"))
        batch_op.drop_index(batch_op.f("ix_crafters_recipes_result_item_id"))

    op.drop_table("crafters_recipes")
    # ### end Alembic commands ###
