"""initial roster tables

Revision ID: 8befe9e08960
Revises:
Create Date: 2026-09-30 18:06:01.485207
"""

import sqlalchemy as sa
from alembic import op

revision = "8befe9e08960"
down_revision = None
branch_labels = ("roster",)
depends_on = "694091f4034e"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roster_officer_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["core_members.id"], name=op.f("fk_roster_officer_notes_author_id_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["core_members.id"],
            name=op.f("fk_roster_officer_notes_member_id_core_members"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roster_officer_notes")),
        info={"module": "roster"},
    )
    with op.batch_alter_table("roster_officer_notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roster_officer_notes_member_id"), ["member_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roster_officer_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roster_officer_notes_member_id"))

    op.drop_table("roster_officer_notes")
    # ### end Alembic commands ###
