"""initial vault tables

Revision ID: e5a139aa7833
Revises:
Create Date: 2026-09-30 18:06:08.180675
"""

import sqlalchemy as sa
from alembic import op

revision = "e5a139aa7833"
down_revision = None
branch_labels = ("vault",)
depends_on = ("694091f4034e", "ba3688dc8663")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vault_holdings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_key", sa.String(length=120), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("slot", sa.String(length=60), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core_characters.id"],
            name=op.f("fk_vault_holdings_character_id_core_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["archive_items.id"], name=op.f("fk_vault_holdings_item_id_archive_items"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["core_members.id"], name=op.f("fk_vault_holdings_updated_by_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vault_holdings")),
        sa.UniqueConstraint("character_id", "name_key", name=op.f("uq_vault_holdings_character_id")),
        info={"module": "vault"},
    )
    with op.batch_alter_table("vault_holdings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vault_holdings_character_id"), ["character_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vault_holdings_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vault_holdings_name_key"), ["name_key"], unique=False)

    op.create_table(
        "vault_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=True),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decided_by", sa.Integer(), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("decision_note", sa.String(length=300), nullable=True),
        sa.Column("fulfilled_from", sa.Integer(), nullable=True),
        sa.Column("discord_channel_id", sa.String(length=30), nullable=True),
        sa.Column("discord_message_id", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["core_members.id"], name=op.f("fk_vault_requests_decided_by_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["fulfilled_from"],
            ["core_characters.id"],
            name=op.f("fk_vault_requests_fulfilled_from_core_characters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["archive_items.id"], name=op.f("fk_vault_requests_item_id_archive_items"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"], ["core_members.id"], name=op.f("fk_vault_requests_requester_id_core_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vault_requests")),
        info={"module": "vault"},
    )
    with op.batch_alter_table("vault_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vault_requests_requester_id"), ["requester_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vault_requests_status"), ["status"], unique=False)

    op.create_table(
        "vault_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("qty_after", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("request_id", sa.Integer(), nullable=True),
        sa.Column("via", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["core_members.id"], name=op.f("fk_vault_transactions_actor_id_core_members")
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["core_characters.id"],
            name=op.f("fk_vault_transactions_character_id_core_characters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["archive_items.id"],
            name=op.f("fk_vault_transactions_item_id_archive_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["vault_requests.id"], name=op.f("fk_vault_transactions_request_id_vault_requests")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vault_transactions")),
        info={"module": "vault"},
    )
    with op.batch_alter_table("vault_transactions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vault_transactions_character_id"), ["character_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_vault_transactions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_vault_transactions_item_id"), ["item_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vault_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vault_transactions_item_id"))
        batch_op.drop_index(batch_op.f("ix_vault_transactions_created_at"))
        batch_op.drop_index(batch_op.f("ix_vault_transactions_character_id"))

    op.drop_table("vault_transactions")
    with op.batch_alter_table("vault_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vault_requests_status"))
        batch_op.drop_index(batch_op.f("ix_vault_requests_requester_id"))

    op.drop_table("vault_requests")
    with op.batch_alter_table("vault_holdings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vault_holdings_name_key"))
        batch_op.drop_index(batch_op.f("ix_vault_holdings_item_id"))
        batch_op.drop_index(batch_op.f("ix_vault_holdings_character_id"))

    op.drop_table("vault_holdings")
    # ### end Alembic commands ###
